# Generated by Django 5.0.1 on 2024-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
