# Generated by Django 5.0.1 on 2024-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parik_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='to_wrap',
            field=models.BooleanField(default=False),
        ),
    ]
