# Generated by Django 5.0.1 on 2024-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parik_to_wrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='background',
            field=models.CharField(default='#222222', max_length=100),
        ),
        migrations.AddField(
            model_name='parik',
            name='color',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
        migrations.AddField(
            model_name='parik',
            name='font',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='parik',
            name='font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='parik',
            name='font_weight',
            field=models.IntegerField(default=100),
        ),
    ]
