# Generated by Django 5.0.1 on 2024-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parik_background_parik_color_parik_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='animation_type',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='parik',
            name='font',
            field=models.CharField(default='inherit', max_length=100),
        ),
        migrations.AlterField(
            model_name='parik',
            name='font_size',
            field=models.IntegerField(default=30),
        ),
    ]
