# Generated by Django 5.0.1 on 2024-02-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parik_animation_type_alter_parik_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='shuffle_colors_by_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parik',
            name='shuffle_fonts_by_line',
            field=models.BooleanField(default=False),
        ),
    ]
