# Generated by Django 5.0.1 on 2024-02-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_font_fontcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='parik',
            name='animation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animation'),
        ),
    ]
