# Generated by Django 5.0.1 on 2024-02-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_parik_animation_type_parik_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parik',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.animation'),
        ),
    ]
