# Generated by Django 5.0.1 on 2024-02-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_parik_animation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animation',
        ),
    ]
