# Generated by Django 5.0.1 on 2024-02-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_channel_channelsubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsubscriber',
            old_name='subsciber',
            new_name='subscriber',
        ),
    ]
