# Generated by Django 5.0.1 on 2024-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_channelsubscriber_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsubscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
