# Generated by Django 5.0.1 on 2024-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_channelsubscriber_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
