# Generated by Django 5.0.2 on 2024-02-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_channelsubscriber_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parik',
            name='font_size',
            field=models.FloatField(default=30),
        ),
    ]
