# Generated by Django 4.2.10 on 2024-03-05 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_instantparik_is_user_saved_instantparik_parik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantparik',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instantparik',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parik',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
