# Generated by Django 4.2.10 on 2024-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_instantparik_title_alter_instantparik_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAPIKEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
    ]
