# Generated by Django 4.2.10 on 2024-03-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_serviceapikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceAPIKEY',
        ),
    ]
