# Generated by Django 4.2.10 on 2024-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_postviewstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviewstat',
            name='last_viewed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
