# Generated by Django 4.2.10 on 2024-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_postviewstat_last_viewed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
