# Generated by Django 4.2.10 on 2024-03-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_channel_about_alter_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='small_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='small_thumbnails'),
        ),
    ]
