# Generated by Django 4.2.10 on 2024-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_channel_small_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='parik',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
